In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('data.csv')
df.shape

(319795, 18)

In [5]:
df.head()

HeartDisease    BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  \
0           No  16.60     Yes              No     No             3.0   
1           No  20.34      No              No    Yes             0.0   
2           No  26.58     Yes              No     No            20.0   
3           No  24.21      No              No     No             0.0   
4           No  23.71      No              No     No            28.0   

   MentalHealth DiffWalking     Sex  AgeCategory   Race Diabetic  \
0          30.0          No  Female        55-59  White      Yes   
1           0.0          No  Female  80 or older  White       No   
2          30.0          No    Male        65-69  White      Yes   
3           0.0          No  Female        75-79  White       No   
4           0.0         Yes  Female        40-44  White       No   

  PhysicalActivity  GenHealth  SleepTime Asthma KidneyDisease SkinCancer  
0              Yes  Very good        5.0    Yes            No        Yes  
1              Yes  Very good        7.0     No            No         No  
2              Yes       Fair        8.0    Yes            No         No  
3               No       Good        6.0     No            No        Yes  
4              Yes  Very good        8.0     No            No         No

In [ ]:
# df.info()

In [8]:
df['HeartDisease'].value_counts()

No     292422
Yes     27373
Name: HeartDisease, dtype: int64

In [31]:
df["AgeCategory"].unique()

array(['55-59', '80 or older', '65-69', '75-79', '40-44', '70-74',
       '60-64', '50-54', '45-49', '18-24', '35-39', '30-34', '25-29'],
      dtype=object)

In [32]:
def pre_process(a):
    if a == '80 or older':
        s = (80+84)/2
    else:
        a = a.split('-')
        s = (int(a[0])+int(a[1]))/2
    return s

In [33]:
pre_process('55-59')

57.0

In [38]:
col = ["HeartDisease","Smoking","AlcoholDrinking","Stroke","DiffWalking","Diabetic","PhysicalActivity","Asthma","KidneyDisease","SkinCancer"]

In [39]:
binary = {"No":0,"Yes":1}
sex = {"Female":0,"Male":1}
GenHealth = {'Very good':0, 'Fair':1, 'Good':2, 'Poor':3, 'Excellent':4}
race = {'White':0, 'Black':1, 'Asian':2, 'American Indian/Alaskan Native':3,
       'Other':4, 'Hispanic':5}

In [40]:
for i in col:
    df[i] = df[i].replace(binary)

In [42]:
df['Sex']=df['Sex'].replace(sex)
df['GenHealth']=df['GenHealth'].replace(GenHealth)
df['Race'] = df['Race'].replace(race)

In [55]:
for j in range(len(df['AgeCategory'])):
    df['AgeCategory'][j] = pre_process(df['AgeCategory'][j])

In [56]:
df.head()

HeartDisease    BMI  Smoking  AlcoholDrinking  Stroke  PhysicalHealth  \
0             0  16.60        1                0       0             3.0   
1             0  20.34        0                0       1             0.0   
2             0  26.58        1                0       0            20.0   
3             0  24.21        0                0       0             0.0   
4             0  23.71        0                0       0            28.0   

   MentalHealth  DiffWalking  Sex AgeCategory  Race Diabetic  \
0          30.0            0    0        57.0     0        1   
1           0.0            0    0        82.0     0        0   
2          30.0            0    1        67.0     0        1   
3           0.0            0    0        77.0     0        0   
4           0.0            1    0        42.0     0        0   

   PhysicalActivity  GenHealth  SleepTime  Asthma  KidneyDisease  SkinCancer  
0                 1          0        5.0       1              0           1  
1                 1          0        7.0       0              0           0  
2                 1          1        8.0       1              0           0  
3                 0          2        6.0       0              0           1  
4                 1          0        8.0       0              0           0

In [57]:
df1 = df[:150000]

In [90]:
df1 = pd.read_csv('df1.csv')
df1.drop(['Unnamed: 0'],axis=1,inplace=True)

In [93]:
df1.head()

HeartDisease    BMI  Smoking  AlcoholDrinking  Stroke  PhysicalHealth  \
0             0  16.60        1                0       0             3.0   
1             0  20.34        0                0       1             0.0   
2             0  26.58        1                0       0            20.0   
3             0  24.21        0                0       0             0.0   
4             0  23.71        0                0       0            28.0   

   MentalHealth  DiffWalking  Sex  AgeCategory  Race Diabetic  \
0          30.0            0    0         57.0     0        1   
1           0.0            0    0         82.0     0        0   
2          30.0            0    1         67.0     0        1   
3           0.0            0    0         77.0     0        0   
4           0.0            1    0         42.0     0        0   

   PhysicalActivity  GenHealth  SleepTime  Asthma  KidneyDisease  SkinCancer  
0                 1          0        5.0       1              0           1  
1                 1          0        7.0       0              0           0  
2                 1          1        8.0       1              0           0  
3                 0          2        6.0       0              0           1  
4                 1          0        8.0       0              0           0

In [94]:
df_1 = df1[df1['HeartDisease']==0]
df_2 = df1[df1['HeartDisease']!=0]

In [95]:
row1 = df_1.sample(n = 50000)
row2 = df_2.sample(n=50000,replace=True)

In [96]:
df_f = pd.concat([row1,row2])

In [105]:
df_f['Diabetic'] = df_f['Diabetic'].replace({'0':0,'1':1})

In [106]:
df_f.head()

HeartDisease    BMI  Smoking  AlcoholDrinking  Stroke  PhysicalHealth  \
62111              0  30.27        1                0       0             2.0   
63513              0  19.65        0                0       0             0.0   
93234              0  30.41        0                0       0             0.0   
103780             0  20.98        1                1       0             0.0   
20848              0  26.58        1                1       0             0.0   

        MentalHealth  DiffWalking  Sex  AgeCategory  Race  Diabetic  \
62111            0.0            0    1         67.0     0         0   
63513            5.0            0    0         57.0     0         0   
93234            0.0            0    1         67.0     0         0   
103780           2.0            0    0         27.0     5         0   
20848            0.0            0    1         37.0     5         1   

        PhysicalActivity  GenHealth  SleepTime  Asthma  KidneyDisease  \
62111                  1          0        6.0       0              0   
63513                  1          4        7.0       0              0   
93234                  1          4        8.0       0              0   
103780                 1          0        7.0       0              0   
20848                  1          2        8.0       0              0   

        SkinCancer  
62111            1  
63513            0  
93234            1  
103780           0  
20848            0

In [108]:
x = df_f.drop(["HeartDisease"],axis=1)
y = df_f['HeartDisease']

In [107]:
df_f['Diabetic'].unique()

array([0, 1], dtype=int64)

In [109]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [110]:
import xgboost as xgb

xgbcl = xgb.XGBClassifier()
xgbcl.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [111]:
pred = xgbcl.predict(x_test)
pred

array([1, 1, 0, ..., 0, 1, 1])

In [113]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.7991818181818182

In [115]:
import pickle
filename = 'finalized_model.sav'
pickle.dump(xgbcl, open(filename, 'wb'))

loaded_model = pickle.load(open(filename, 'rb'))
test = loaded_model.predict(x_test)
test

array([1, 1, 0, ..., 0, 1, 1])